### ISSUE TITLE
bash run.sh  failed

### ISSUE THREAD

**Issue by gcMs1** [fan-ziqi/rl_docker#1]
您好，今天在运行您发布docker环境的配置过程中出现问题，具体如下：
![截图 2023-12-13 17-42-07](https://github.com/fan-ziqi/rl_docker/assets/100077449/3673d995-3b75-4cae-a9f6-0693e92fd26a)
我的系统环境如下：
ubuntu22.04
nvidia-smi: 
![截图 2023-12-13 17-45-18](https://github.com/fan-ziqi/rl_docker/assets/100077449/5a8df98a-0074-47a7-85e7-5331e656dce5)
docker --version: Docker version 24.0.7
请问该怎么解决呢，期待您的回复

**Comment by fan-ziqi** [comment]
第一张图下面报错找不到isaacgym包
1. 根目录是否存在 `isaacgym` 这个包？
2. 是否自定义并检查过 `setup.sh` 的内容？

---

Error message below the first image: isaacgym package not found
1. Does the `isaacgym` package exist in the root directory?
2. Have you customized and checked the content of `setup.sh` ?

**Comment by fan-ziqi** [comment]
查看 https://github.com/fan-ziqi/rl_docker/commit/d83305ab6b87abf153830939568489eb5c8d6af7

---

See https://github.com/fan-ziqi/rl_docker/commit/d83305ab6b87abf153830939568489eb5c8d6af7

**Comment by gcMs1** [comment]
好的感谢解答
