### ISSUE TITLE
Error at start bash run.sh 

### ISSUE THREAD

**Issue by RubSevian** [fan-ziqi/rl_docker#3]
When starting a line bash run.sh -g all -d true , I see error 
![Screenshot from 2024-05-31 00-33-23](https://github.com/fan-ziqi/rl_docker/assets/109359327/b994f075-bf46-48fa-b7af-c605337e22bf)

If I, as root, go to /home/root.../setup.sh, then I will encounter a new problem
![Screenshot from 2024-05-31 00-36-11](https://github.com/fan-ziqi/rl_docker/assets/109359327/2797bd1f-c77f-4335-afc8-2e52cad364ee)

Please tell me how I can avoid these mistakes
I use Ubuntu20.04 and RTX3060 12GB

**Comment by wghou** [comment]
Hi, RubSevian! I got the same mistake. Please let me know how I can fixed it. Thanks a lot!
@RubSevian
